### ISSUE TITLE
RE Model Corpus & Dataset Mismatch

### ISSUE THREAD

**Issue by zehao-sean-huang** [pinkymm/inconsistency_detection#3]
## Reproduce

I am constantly getting the error below when training the RE model using the corpus you provided. 

```
Traceback (most recent call last):
  File "/home/zehaohuang/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/zehaohuang/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/zehaohuang/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[190,29] = 82096 is not in [0, 82054)
	 [[{{node model/embedding_lookup_3}}]]
```

It appears that the function `init_train_data` in `initial_RE.py` is generating indices larger than the length of the word embedding. After taking a look into the details, int lines `[291, 304]`, the code writes:

```python
if sentence[i] not in word2id:
    ps = sentence[i].split('_')
    # avg_vec = np.zeros(commons.word_emb_dim)
    c = 0
    for p in ps:
        if p in word2id:
            c += 1
            # avg_vec += vec[word2id[p]]
    if c > 0:
        # avg_vec = avg_vec / c
        word2id[sentence[i]] = len(word2id)
        #vec.append(avg_vec)
    else:
        word = word2id['UNK']
```

Then later in the tensorflow embedding lookup function (`networkRE.py:134`): `tf.nn.embedding_lookup(word_embedding, tf.reverse(self.input_word, [1])),` invokes an index out of bound error because in the code above you are expanding the index on the fly without complying to the word embedding dimension predefined. 

## Advise:

* You can provide a more comprehensive corpus.
* Is it safe to mark all words as `UNK`? How would that impact the training outcome? 

Please advise. Thanks!

**Comment by zehao-sean-huang** [comment]
Has there been any update on this? Thanks!
